typography_spectrum: 0.8116713010240346
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0.74942
title: ++ music is the universal language ++
purpose: []
color:
  saturation: 0.03226439328864217
  brandStrength: 0.4784946
  rhythmicContrast: 0.5573051555547863
  brandColors:
    - '#FFFFFF'
    - '#1D1D1B'
    - '#5C5C5C'
    - '#929292'
    - '#C7C7C7'
  lightness: 0.4435452241450548
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Chris Marina
