name: Chris Marina
favicon: null
layout_spectrum: 0.6105600211303681
typography_spectrum: 0.8116713010240346
title: ++ music is the universal language ++
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6474178463686258
  lightness: 0.4435452241450548
  saturation: 0.03226439328864217
  rhythmicContrast: 0.5573051555547863
purpose: []
